// src/utils/mockData.ts

export const mockMovies = [
  {
    id: '1',
    title: 'Inception',
    year: 2010,
    producer: 'Emma Thomas',
    actors: ['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Elliot Page'],
  },
  {
    id: '2',
    title: 'The Dark Knight',
    year: 2008,
    producer: 'Charles Roven',
    actors: ['Christian Bale', 'Heath Ledger', 'Aaron Eckhart'],
  },
  {
    id: '3',
    title: 'Interstellar',
    year: 2014,
    producer: 'Emma Thomas',
    actors: ['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain'],
  },
  {
    id: '4',
    title: 'The Matrix',
    year: 1999,
    producer: 'Joel Silver',
    actors: ['Keanu Reeves', 'Laurence Fishburne', 'Carrie-Anne Moss'],
  },
  {
    id: '5',
    title: 'Parasite',
    year: 2019,
    producer: 'Kwak Sin-ae',
    actors: ['Song Kang-ho', 'Lee Sun-kyun', 'Cho Yeo-jeong'],
  },
  {
    id: '6',
    title: 'The Shawshank Redemption',
    year: 1994,
    producer: 'Niki Marvin',
    actors: ['Tim Robbins', 'Morgan Freeman', 'Bob Gunton'],
  },
  {
    id: '7',
    title: 'Forrest Gump',
    year: 1994,
    producer: 'Wendy Finerman',
    actors: ['Tom Hanks', 'Robin Wright', 'Gary Sinise'],
  },
  {
    id: '8',
    title: 'The Godfather',
    year: 1972,
    producer: 'Albert S. Ruddy',
    actors: ['Marlon Brando', 'Al Pacino', 'James Caan'],
  },
  {
    id: '9',
    title: 'Pulp Fiction',
    year: 1994,
    producer: 'Lawrence Bender',
    actors: ['John Travolta', 'Uma Thurman', 'Samuel L. Jackson'],
  },
  {
    id: '10',
    title: 'Avengers: Endgame',
    year: 2019,
    producer: 'Kevin Feige',
    actors: ['Robert Downey Jr.', 'Chris Evans', 'Scarlett Johansson'],
  },
  {
    id: '11',
    title: 'Forrest Gump',
    year: 1994,
    producer: 'Wendy Finerman',
    actors: ['Tom Hanks', 'Robin Wright', 'Gary Sinise'],
  },
  {
    id: '12',
    title: 'The Godfather',
    year: 1972,
    producer: 'Albert S. Ruddy',
    actors: ['Marlon Brando', 'Al Pacino', 'James Caan'],
  },
  {
    id: '13',
    title: 'Pulp Fiction',
    year: 1994,
    producer: 'Lawrence Bender',
    actors: ['John Travolta', 'Uma Thurman', 'Samuel L. Jackson'],
  },
  {
    id: '14',
    title: 'Avengers: Endgame',
    year: 2019,
    producer: 'Kevin Feige',
    actors: ['Robert Downey Jr.', 'Chris Evans', 'Scarlett Johansson'],
  },
];
